module.exports = {
  //only superadmin section
  "users.read": ["super_admin"],
  "users.write": ["super_admin"],
  "users.delete": ["super_admin"],
  "users.export": ["super_admin"],
  "agencies.read": ["super_admin"],
  "agencies.write": ["super_admin"],
  "agencies.delete": ["super_admin"],
  //superAdmin and admin sections
  "roles.read": ["super_admin", "admin"],
  "packages.read": ["super_admin", "admin"],
  "packages.write": ["super_admin", "admin"],
  "packages.delete": ["super_admin", "admin"],
  "subscriptions.write": ["super_admin"],
  "branches.read": ["super_admin", "admin"],
  "branches.write": ["super_admin", "admin"],
  "branches.delete": ["super_admin", "admin"],
  "countries.write": ["super_admin", "admin"],
  "countries.delete": ["super_admin", "admin"],
  "countries.read": ["super_admin", "admin"],
  "states.write": ["super_admin", "admin"],
  "states.delete": ["super_admin", "admin"],
  "states.read": ["super_admin", "admin"],
  "cities.write": ["super_admin", "admin"],
  "cities.delete": ["super_admin", "admin"],
  "cities.read": ["super_admin", "admin"],
  "sectors.write": ["super_admin", "admin"],
  "sectors.delete": ["super_admin", "admin"],
  "sectors.read": ["super_admin", "admin"],
};
